# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619c838ce0d1219d675ad19cea325ddf0bccd88e9b6e9e430e0ab2b7d8d51931825768fb4e835197dcc21155b60b201d3d0836505a0a9786ee3950cd3f9c52d0

test:
  secret_key_base: 6c7535d23084d0476a0b938fcff1c5ff39830bb3fa27370874841e6174808e8c4836c7f87d6b42c93d98338d60b66ec0cc4754bda4026b008fe7c42d5341072f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
